name = "newera"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

account_id = "69becb9b62eb7ca72839b96d069cc630"

[[d1_databases]]
binding = "DB"
database_name = "newera"
database_id = "a338ad64-7878-4269-84e1-e019a26e1756"

[[r2_buckets]]
binding = "RELEASES_BUCKET"
bucket_name = "releases"

[vars]
NEXT_PUBLIC_R2_PUBLIC_URL_RELEASES = "https://releases.breakoutmusic.online"
